model_config:
  vitbert:
    training_head_type: classification
    num_labels: 2
    losses:
    - cross_entropy
    v_hidden_size: 768
    v_seq_len: 197
    image_size: 224
    patch_size: 16
    num_channels: 3


dataset_config:
  hateful_memes:
    use_images: true
    use_features: false
    # use_images: false
    # use_features: true
    return_features_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: bbox
          image_width_key: image_width
          image_height_key: image_height
      image_processor:
        type: torchvision_transforms
        params:
          transforms:
            - type: Resize
              params:
                size: [224, 224]
            - ToTensor
            - GrayScaleTo3Channels
            - type: Normalize
              params:
                mean: [0.46777044, 0.44531429, 0.40661017]
                std: [0.12221994, 0.12145835, 0.14380469]


optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

evaluation:
  metrics:
  - accuracy
  - binary_f1
  - roc_auc

training:
  experiment_name: vitbert-small
  batch_size: 32
  lr_scheduler: true
  max_updates: 10000
  find_unused_parameters: true
  early_stop:
    criteria: hateful_memes/roc_auc
    minimize: false
  wandb: 
    enabled: true
    entity: null
    project: mmf 
    log_checkpoint: true
checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
        
env:
    # To change the path to the directory where wandb metadata would be 
    # stored (Default: env.log_dir):
  wandb_projectname: mmf


